# Generated by Django 6.0.2 on 2026-02-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
    ]
